name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    env:
      CXX: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          if [ "${{ matrix.compiler }}" = "clang++" ]; then
            sudo apt-get install -y clang libomp-dev
          else
            sudo apt-get install -y g++
          fi

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            progetto/build
            progetto/bin
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('progetto/**') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-

      - name: Build and run CPU tests
        working-directory: progetto
        run: make run-seq

      - name: Build and run OpenMP tests
        working-directory: progetto
        run: make OMP=1 run-omp
